policy_name: "global_policy"
policy_action: "platform-max"
link_aggregation_pref: "port-channel"
multicast_hw_hash: "enabled"
redundancy: "non-redundant"
port_name: "ether"
FI_id_A: "A"
FI_id_B: "B"
ether_ports:
  - name: "Uplink_port_1"
    port_id: "33"
    slot_id: "1"
    port_type: "network"
  - name: "Uplink_port_2"
    port_id: "34"
    slot_id: "1"
    port_type: "network"
  - name: "Chassis_1_port_1"
    port_id: "17"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_1_port_2"
    port_id: "18"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_1_port_3"
    port_id: "19"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_1_port_4"
    port_id: "20"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_2_port_1"
    port_id: "21"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_2_port_2"
    port_id: "22"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_2_port_3"
    port_id: "23"
    slot_id: "1"
    port_type: "server"
  - name: "Chassis_2_port_4"
    port_id: "24"
    slot_id: "1"
    port_type: "server"
  - name: "Server_1"
    port_id: "25"
    slot_id: "1"
    port_type: "server"
  - name: "Server_2"
    port_id: "26"
    slot_id: "1"
    port_type: "server"
  - name: "Sever_3"
    port_id: "27"
    slot_id: "1"
    port_type: "server"
