provider_ssh:
  host: "{{ nexus_hosts }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: cli
provider_nxapi:
  host: "{{ nexus_hosts }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: no
  port: 443
enabled_features:
  - lacp
  - vpc
  - interface-vlan
  - nxapi
  - udld
